function ComponentsBehavePlot(CAIM,mouse,session,nums,gain)

A = CAIM(session,mouse).A;
C = CAIM(session,mouse).C;
FOV = CAIM(session,mouse).FOV;
tsscn = CAIM(session,mouse).behave.tsscn;
speed = CAIM(session, mouse).behave.speed;
distance = CAIM(session, mouse).behave.distance;
dt = tsscn(end)/length(tsscn);


figure('color',[1 1 1]);
pltcol = [0 0 0];
ftsz = 10;


%% FOV

subplot(6,2,[2 4 6 8]-1)

FOV(:,:,3) = gain(1)*FOV(:,:,1);
FOV(:,:,1) = gain(2)*FOV(:,:,2);
FOV(:,:,2) = FOV(:,:,3);
FOV(:,:,3) = 0;
imshow(FOV)

%% spatial components


d1 = size(FOV,1);
d2 = size(FOV,2);

for i = 1:3
    subplot(5,6,24+i)
    temp = full(reshape(A(:,i),d1,d2));
    temp = 2*(mat2gray(temp));
    fa = imshow(temp);
end


%% Plot imaging Data

subplot(6,2,[2 4 6 8])

for i = 1:length(nums)  
    aa = C(nums(i),:);
    aa = mat2gray(aa);
    plot(tsscn(1:end),aa(1:end)+((i-1)),...
        'color',pltcol,...
        'linewidth',1);
    hold on
end
hold off
set(gca,'ylim', [0 length(nums)]);
set(gca,'xlim', [0 tsscn(end)]);
axis off

%% scale bars
fig_pos=get(gca,'position');
yp1=fig_pos(2);
yp2=fig_pos(2)+fig_pos(4)/length(nums);%/(abs(min(aa))+max(aa));%+1/(length(nums)*max(a));
xp1=fig_pos(1)-.008;
xp2=xp1+fig_pos(3)/length(aa)/dt*1000;


% h1 = annotation('textarrow',[xp1,xp2],[yp1,yp1],...
%        'color',pltcol,...
%        'HeadStyle','none',...       'HeadWidth',6,...       'Headlength',12,...
%        'linewidth',2);
       
h2 = annotation('textarrow',[xp1,xp1],[yp1+.18,yp1+.18],...
       'color',pltcol,...
       'HeadStyle','none',...
       'string','100% \DeltaF/F',...
       'fontsize',ftsz,...
       'VerticalAlignment','bottom',...  
       'TextRotation',90,...
       'HorizontalAlignment','right');

h3 = annotation('textarrow',[xp1,xp1],[yp1,yp2],...
       'color',pltcol,...
       'HeadStyle','none',...
       'HeadWidth',6,...
       'Headlength',12,...
       'linewidth',2);       

% h4 = annotation('textarrow',[xp1,xp1],[yp1,yp1],...
%        'color',pltcol,...
%        'HeadStyle','none',...
%        'string','10 sec',...        
%        'fontsize',ftsz,...
%        'VerticalAlignment','top',...
%        'TextRotation',0,...
%        'HorizontalAlignment','left');

hold off


%% Movement Plot  
subplot(6,2,10)    

plot(tsscn(1:end),mat2gray(distance),...
        'color',[0 1 1],...
        'linewidth',1);

set(gca,'ylim', [0 1]);
set(gca,'xlim', [0 tsscn(end)]);
axis off
hold on

% Scalebars

lbar = 60; %length of scalebar in seconds    
fig_pos=get(gca,'position');
yp1=fig_pos(2);
yp2=yp1+fig_pos(4);%/(abs(min(aa))+max(aa));%+1/(length(nums)*max(a));
xp1=fig_pos(1); % startpoint for the scale bars
xp2=xp1+lbar*1000*(length(tsscn)/tsscn(end))*(fig_pos(3)/(length(tsscn))); % legnth of the scale bar normalized to length of plot and recording

hcap = annotation('textarrow',[xp1+.055,xp1+.055],[yp2,yp2],...
       'color',pltcol,...
       'HeadStyle','none',...
       'string','Position',...
       'fontsize',ftsz,...
       'VerticalAlignment','bottom',...  
       'HorizontalAlignment','left'); 

h1 = annotation('textarrow',[xp1,xp1],[yp1,yp2],...
       'color',pltcol,...
       'HeadStyle','none',...       'HeadWidth',6,...       'Headlength',12,...
       'linewidth',1);
   
h3 = annotation('textarrow',[xp1,xp1],[yp1,yp1],...
   'color',pltcol,...
   'HeadStyle','none',...
   'string','0',...
   'fontsize',ftsz-5,...
   'VerticalAlignment','middle',...  
   'HorizontalAlignment','right');    

h4 = annotation('textarrow',[xp1,xp1],[yp2,yp2],...
   'color',pltcol,...
   'HeadStyle','none',...
   'string','1.5 m',...
   'fontsize',ftsz-5,...
   'VerticalAlignment','middle',...  
   'HorizontalAlignment','right');     
    

% timescalebar

xp1=fig_pos(1)+fig_pos(3)-lbar*1000*(length(tsscn)/tsscn(end))*(fig_pos(3)/(length(tsscn))); 
xp2=xp1+lbar*1000*(length(tsscn)/tsscn(end))*(fig_pos(3)/(length(tsscn))); % legnth of the scale bar normalized to length of plot and recording
    
h3 = annotation('textarrow',[xp1,xp2],[yp1,yp1],...
       'color',pltcol,...
       'HeadStyle','none',...
       'HeadWidth',6,...
       'Headlength',12,...
       'linewidth',2); 
   
h4 = annotation('textarrow',[xp2,xp2],[yp1,yp1],...
       'color',pltcol,...
       'HeadStyle','none',...
       'string','1 min',...        
       'fontsize',ftsz,...
       'VerticalAlignment','top',...
       'TextRotation',0,...
       'HorizontalAlignment','left');
    
hold off
   

end
   